on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false

      # https://docs.typo3.org/m/typo3/tutorial-getting-started/11.5/en-us/Installation/TutorialDdev.html
      - run: |
          ddev -v \
          ddev config --project-type=typo3 --docroot=public \
          ddev start -y \
          ddev composer create "typo3/cms-base-distribution:^11" \ 
          ddev typo3cms install:setup --admin-user-name="admin" --admin-password="password123" --site-name="test" \
          ddev launch typo3

      # TODO: Check for http=200?
