on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - run: mkdir ddev-tmp-project-folder/
      
      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false
          ddevDir: ddev-tmp-project-folder

      # https://docs.typo3.org/m/typo3/tutorial-getting-started/11.5/en-us/Installation/TutorialDdev.html
      - run: |
          ddev -v
          ddev config  --project-type=typo3 --docroot=public --php-version 8.2
          ddev start -y
          ddev composer create "typo3/cms-base-distribution:^13"
          ddev exec ./vendor/bin/typo3 setup --admin-username="admin" --admin-user-password="password123" --project-name="test"
          # ddev launch typo3
        working-directory: ddev-tmp-project-folder

      # TODO: Check somehow for http=200 on front- and backend?
